### PR TITLE
Fix a couple of issues with Do and exceptions

### LINKED ISSUE #33: Issues with mocking a method to throw an exception
Hi,

I found two annoying issues when mocking a method to throw an exception:

1. When doing the following, the exception is thrown but "called" will stay false:
`bool called = false;`
`mock.When(x => x.SomeMethod()).Do(() => called = true).Throw()`
`try { mock.SomeMethod(); }`
`catch { }`
2. When throwing an exception in the Do action, it will be wrapped under a TargetInvocationException:
`mock.When(x => x.SomeMethod()).Do(() => throw new MyException())`
`try { mock.SomeMethod(); }`
`catch (MyException) { /* Will never go there. */ }`
`catch (TargetInvocationException) { /* Will go there instead. */ }`

Thanks for all the nice work!

### PR DESCRIPTION
**Pull request by kentcb**
Fixes #33

### CODE REVIEW

File: Src/PCLMock/WhenContinuation.cs [hunk 1]
```diff
@@ -346,15 +347,26 @@ internal override object Apply(object mockedObject, params object[] args)
         {
             Debug.Assert(args != null);
 
-            if (this.exception != null)
+            if (this.doAction != null)
```
Comment (kentcb) [inline Src/PCLMock/WhenContinuation.cs:350]: Checking the `doAction` first now so that it executes even if there's a throw afterwards.

File: Src/PCLMock/WhenContinuation.cs [hunk 2]
```diff
@@ -346,15 +347,26 @@ internal override object Apply(object mockedObject, params object[] args)
...
+                {
+                    this.doAction.DynamicInvoke(args);
+                }
+                catch (TargetInvocationException ex)
+                {
+                    // Unwrap the inner exception and preserve its stack trace.
+                    ExceptionDispatchInfo
+                        .Capture(ex.InnerException)
+                        .Throw();
+                }
```
Comment (kentcb) [inline Src/PCLMock/WhenContinuation.cs:364]: This is critical to ensuring the exception that is thrown by the `Do` invocation makes sense to the caller.
